name: happy_messanger
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  permission_handler: ^9.2.0
  fast_contacts: ^1.1.1
  logger: ^1.1.0
  get: 4.6.1
  flutter: 
    sdk: flutter
  google_fonts: ^2.3.2
  font_awesome_flutter:
  curved_navigation_bar: ^1.0.3
  firebase_core: ^1.16.0
  google_sign_in: ^5.3.0
  firebase_auth: ^3.3.17
  flutter_easyloading: ^3.0.3
  flutter_slidable: ^1.2.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_sms: ^2.3.2
  flutter_neumorphic: ^3.2.0
  get_storage: ^2.0.3
  share_plus: ^4.0.4
  image_picker: ^0.8.5+2
  image_preview: ^1.0.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: AkayaTelivigala
      fonts:
        - asset: assets/fonts/AkayaKanadaka-Regular.ttf

