name: happy_messanger
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  permission_handler: ^9.2.0
  fast_contacts: ^1.1.1
  logger: ^1.1.0
  get: 4.6.1
  flutter: 
    sdk: flutter
  google_fonts: ^2.3.2
  curved_navigation_bar: ^1.0.3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: AkayaTelivigala
      fonts:
        - asset: assets/fonts/AkayaKanadaka-Regular.ttf

